### ISSUE TITLE
Flag body width bug in Webkit/Blink based browsers

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/objects.flag#5]
There is a bug with `.flag__body` in Webkit/Blink based browsers if its parent is table cell (actually `display: table-cell`, I didn't check actual tables). It seems to take more space than it should. Let me demonstrate it [here](http://codepen.io/nenadjelovac/pen/mhJwz). If you check it in Firefox you will see how it should behave.

The fix is to remove `width: 100%` from `.flag__body` (or explicitly set it to `width: auto` just to be sure) and set `width: 1px` to `.flag__img`. I have picked up the fix from [an old(ish) article here](http://pixelsvsbytes.com/blog/2012/02/this-css-layout-grid-is-no-holy-grail/?phpMyAdmin=0ZRJj6JUwx3do5nBBGsib-MdEm7). Here's what the author has to say about this:

> **By setting height/width:1px a normal cell will use the minimum amount of space to display its contents**, leaving all unused space for the .Expand class cells with height/width:auto.

And [here's a pen for the fix](http://codepen.io/nenadjelovac/pen/Govgj). This probably needs more testing, but it seems to not mess things up.

**Comment by florianbouvot** [comment]
@zerodburn you can may be close this issue ?

**Comment by patrick-wc** [comment]
I can't, didn't open it.

**Comment by nenadjelovac** [comment]
@florianbouvot no, the issue is different than what @zerodburn posted later in comments. We're still waiting for @csswizardry to make some time to check this out :)

**Comment by florianbouvot** [comment]
You have right, sorry @nenadjelovac

**Comment by nenadjelovac** [comment]
@csswizardry @anselmh @florianbouvot @csshugs have you guys had this issue? 

I've implemented the fix from first comment in several projects and it all seems to work great.

**Comment by anselmh** [comment]
Actually there’s still a difference in widhts between the Chrome and Firefox with the fix applied. As this seems to be a hacky trick which seems not to work 100% fine I’d opt-out baking it in by default but honestly I don’t use the flag object too often.
I’d recommend opening a bug in the WebKit/Blink tracker and see if it’ll get fixed in the engine which would be a better solution.

**Comment by nenadjelovac** [comment]
> Actually there’s still a difference in widhts between the Chrome and Firefox with the fix applied.

Yeah, but that's just a minor thing (few px here and there) related to font rendering. And IMO that's way better than the situation [without the fix](http://codepen.io/nenadjelovac/pen/mhJwz).

> As this seems to be a **hacky** trick which seems not to work 100% fine I’d opt-out baking it in by default but honestly I don’t use the flag object too often.

That's why I asked for first-hand experience from other people using flag object. I've personally run into this bug quite often and proposed fix did the trick. 
Also, `.flag__body` having 100% width is hacky as well.

> The width:100% on the .flag__body{} is an odd hack of sorts; this forces the text content to take up all of the space that the .flag__image{} does not.

Source: http://csswizardry.com/2013/05/the-flag-object/

> I’d recommend opening a bug in the WebKit/Blink tracker and see if it’ll get fixed in the engine which would be a better solution.

While this is a good idea, it is future fix only. So if you support iOS 7 you have to do the fix in your css.

**Comment by anselmh** [comment]
Does anyone know which browsers are currently affected by that? Can we get a short list to elaborate if it’s worth fixing this? Massive thanks in advance. + @nenadjelovac

**Comment by florianbouvot** [comment]
@nenadjelovac don't know if it can help but if you switch `width` to `min-width` on `.table` it works:

```
.table {
  display: table;
  min-width: 100%;
}
```

**Comment by florianbouvot** [comment]
@nenadjelovac fixed in new inuitcss version [objects.flag](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.flag.scss), can we close this issue?
